import type { OpportunityArchetype } from "@/lib/opportunity-discovery-v2/types";
import type { CoverageVariableKey } from "./types";

export const ARCHETYPE_REQUIREMENTS_V1: Record<OpportunityArchetype, { required: CoverageVariableKey[]; optional: CoverageVariableKey[] }> = {
  SPORTS_EVENT_ACTIVATION: {
    required: ["IDENTITY_COVERAGE", "TRIGGER_CONTEXT", "TIMING_CONTEXT", "BUYER_INTENT", "COMMERCIAL_CONTEXT"],
    optional: ["ACCESS_CONTEXT", "PROGRAM_SURFACES", "VALUATION_INPUTS", "CONTACT_COVERAGE"]
  },
  VIP_RELATIONSHIP_GIFTING: {
    required: ["IDENTITY_COVERAGE", "ACCESS_CONTEXT", "BUYER_INTENT", "VALUATION_INPUTS"],
    optional: ["CONTACT_COVERAGE", "COMMERCIAL_CONTEXT", "TRIGGER_CONTEXT"]
  },
  CORPORATE_GIFTING_RELATIONSHIP_ART: {
    required: ["IDENTITY_COVERAGE", "ACCESS_CONTEXT", "BUYER_INTENT", "COMMERCIAL_CONTEXT"],
    optional: ["CONTACT_COVERAGE", "VALUATION_INPUTS"]
  },
  CHARITY_TALENT_CAMPAIGN: {
    required: ["IDENTITY_COVERAGE", "TRIGGER_CONTEXT", "TIMING_CONTEXT", "BUYER_INTENT"],
    optional: ["COMMERCIAL_CONTEXT", "ACCESS_CONTEXT", "CONTACT_COVERAGE", "VALUATION_INPUTS"]
  },
  CORPORATE_MILESTONE_ART: {
    required: ["IDENTITY_COVERAGE", "TRIGGER_CONTEXT", "TIMING_CONTEXT", "BUYER_INTENT"],
    optional: ["COMMERCIAL_CONTEXT", "ACCESS_CONTEXT", "VALUATION_INPUTS", "CONTACT_COVERAGE"]
  },
  HALL_OF_FAME_RECURRING_PROGRAM: {
    required: ["IDENTITY_COVERAGE", "PROGRAM_SURFACES", "TIMING_CONTEXT", "BUYER_INTENT", "COMMERCIAL_CONTEXT"],
    optional: ["TRIGGER_CONTEXT", "ACCESS_CONTEXT", "VALUATION_INPUTS", "CONTACT_COVERAGE"]
  },
  CORPORATE_COLLECTION_WORKPLACE_ART: {
    required: ["IDENTITY_COVERAGE", "ORGANIZATION_CONTEXT", "BUYER_INTENT", "COMMERCIAL_CONTEXT"],
    optional: ["ACCESS_CONTEXT", "VALUATION_INPUTS", "CONTACT_COVERAGE"]
  },
  HOSPITALITY_ART: {
    required: ["IDENTITY_COVERAGE", "ORGANIZATION_CONTEXT", "BUYER_INTENT", "COMMERCIAL_CONTEXT"],
    optional: ["ACCESS_CONTEXT", "TIMING_CONTEXT", "VALUATION_INPUTS", "CONTACT_COVERAGE"]
  },
  LICENSING_MERCHANDISING: {
    required: ["IDENTITY_COVERAGE", "COMMERCIAL_CONTEXT", "BUYER_INTENT", "VALUATION_INPUTS"],
    optional: ["PROGRAM_SURFACES", "TRIGGER_CONTEXT", "TIMING_CONTEXT", "ACCESS_CONTEXT", "CONTACT_COVERAGE"]
  },
  RETAIL_DISTRIBUTION: {
    required: ["IDENTITY_COVERAGE", "COMMERCIAL_CONTEXT", "BUYER_INTENT"],
    optional: ["ORGANIZATION_CONTEXT", "ACCESS_CONTEXT", "CONTACT_COVERAGE", "VALUATION_INPUTS"]
  },
  CULTURAL_INSTITUTIONAL: {
    required: ["IDENTITY_COVERAGE", "BUYER_INTENT", "VALUATION_INPUTS", "ACCESS_CONTEXT"],
    optional: ["TIMING_CONTEXT", "TRIGGER_CONTEXT", "CONTACT_COVERAGE", "COMMERCIAL_CONTEXT"]
  }
};

