import test from "node:test";
import assert from "node:assert/strict";

import { ExternalSignalSchema } from "@/lib/external-intelligence/contracts/external-signal";

test("ExternalSignalSchema rejects recommendation/action fields", () => {
  assert.throws(() =>
    ExternalSignalSchema.parse({
      signal_id: "sig1",
      signal_schema_version: "signal_v1",
      interpretation_policy_version: "signal-interpretation/v1.0.0",
      confidence_policy_version: "confidence/v1.0.0",
      disposition_policy_version: "disposition/v1.0.0",
      legal_policy_version: "legal/v1.0.0",
      entity_resolution_version: "entity-resolution/v1.0.0",
      source_registry_version: "source_registry_v1",
      signal_fingerprint: "a".repeat(64),
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      first_observed_at: new Date().toISOString(),
      last_observed_at: new Date().toISOString(),
      lifecycle_status: "candidate",
      supersedes_signal_ids: [],
      superseded_by_signal_id: null,
      signal_type: "rumor",
      signal_classification: "rumor",
      business_domains: [],
      affected_entities: [],
      affected_markets: [],
      geography: null,
      languages: [],
      source_ids: [],
      source_set_ids: [],
      evidence_reference_version_refs: [],
      claim_version_refs: [],
      event_version_refs: [],
      relationship_version_refs: [],
      trend_version_refs: [],
      normalized_statement: "x",
      observed_fact: "x",
      inferred_interpretation: null,
      expected_business_mechanism: null,
      internal_business_relevance: null,
      strategic_fit: null,
      opportunity_relevance: null,
      risk_relevance: null,
      novelty: "unknown",
      urgency: "unknown",
      expiration: new Date().toISOString(),
      review_by: null,
      supporting_evidence: [],
      contradicting_evidence: [],
      missing_evidence: [],
      corroboration_count: 0,
      independent_source_count: 0,
      source_credibility_summary: "",
      signal_credibility: { level: "low", reasons: [] },
      confidence: {
        evidence: { level: "unknown", bounded_score: null, reasons: [], blockers: [], supporting_reference_ids: [], contradicting_reference_ids: [], missing_evidence_ids: [] },
        interpretation: { level: "unknown", bounded_score: null, reasons: [], blockers: [], supporting_reference_ids: [], contradicting_reference_ids: [], missing_evidence_ids: [] },
        business_relevance: { level: "unknown", bounded_score: null, reasons: [], blockers: [], supporting_reference_ids: [], contradicting_reference_ids: [], missing_evidence_ids: [] },
        mechanism: { level: "unknown", bounded_score: null, reasons: [], blockers: [], supporting_reference_ids: [], contradicting_reference_ids: [], missing_evidence_ids: [] },
        timing: { level: "unknown", bounded_score: null, reasons: [], blockers: [], supporting_reference_ids: [], contradicting_reference_ids: [], missing_evidence_ids: [] },
        entity_resolution: { level: "unknown", bounded_score: null, reasons: [], blockers: [], supporting_reference_ids: [], contradicting_reference_ids: [], missing_evidence_ids: [] },
        overall: { level: "unknown", bounded_score: null, reasons: [], blockers: [], supporting_reference_ids: [], contradicting_reference_ids: [], missing_evidence_ids: [] }
      },
      uncertainty_reasons: [],
      what_would_strengthen: [],
      what_would_weaken: [],
      what_would_invalidate: [],
      disposition: "monitor",
      disposition_reason_codes: [],
      escalation_eligibility: "blocked",
      fusion_eligibility: "blocked",
      monitoring_cadence: null,
      relevance_expires_at: new Date().toISOString(),
      archived_at: null,
      extraction_method: "deterministic",
      deterministic_rules_applied: [],
      llm_assistance_used: false,
      model_version: null,
      prompt_version: null,
      human_review_status: null,
      correction_history: [],
      access_classification: "public",
      recommended_action: "do x"
    })
  );
});
