import type { FusionCandidate } from "@/lib/fusion-v1/contracts";

export function buildFusionV1FixtureCandidates(nowIso: string): FusionCandidate[] {
  const in7d = new Date(new Date(nowIso).getTime() + 7 * 24 * 3600 * 1000).toISOString();
  const in2d = new Date(new Date(nowIso).getTime() + 2 * 24 * 3600 * 1000).toISOString();

  // A) Traffic Quality Mismatch candidate (information-gain)
  const trafficQuality: FusionCandidate = {
    candidate_id: "cand_traffic_quality_mismatch",
    candidate_type: "internal_finding_package",
    source_engine: "intelligence_v1_detector",
    source_engine_version: "traffic_quality_mismatch_v1",
    linked_finding_id: "find_traffic_quality_mismatch_v1_2026-07-25_2026-07-31",
    linked_hypothesis_ids: [
      "hyp_traffic_quality_mismatch_v1_1",
      "hyp_traffic_quality_mismatch_v1_2",
      "hyp_traffic_quality_mismatch_v1_3"
    ],
    linked_opportunity_id: "opp_traffic_quality_mismatch_v1",
    linked_recommendation_id: "rec_traffic_quality_mismatch_v1_2026-07-25_2026-07-31",
    recommendation_fingerprint: "FIXTURE_FINGERPRINT_TQM",
    affected_business_domains: ["marketing", "commerce", "website"],
    affected_entities: [],
    supporting_evidence_fact_ids: ["fact_sessions", "fact_conv"],
    contradicting_evidence_fact_ids: [],
    missing_evidence: [
      "GA4 source/medium mix",
      "GA4 device mix",
      "Landing page engagement by segment",
      "Checkout funnel completion"
    ],
    internal_sources_used: ["ga4", "woo"],
    external_signals_used: [],
    external_signals_missing: ["competitive context"],
    expected_mechanism: "traffic mix shift vs funnel friction",
    blocked_domain_constraints: [],
    strategic_guardrail_violations: [],
    confidence: {
      system: "intelligence_v1",
      level: "possible",
      score: 0.55,
      reasons: ["Sessions increased while purchase conversion declined."],
      blockers: ["Need segment breakdown to attribute driver."]
    },
    urgency: "high",
    risk: "medium",
    value_potential_proxy: 0.7,
    information_gain_value: 0.85,
    strategic_fit: 0.9,
    relevance_expires_at: in7d,
    current_regime: null,
    proposed_action: {
      action_key: "diagnose_traffic_quality_segments",
      category: "measurement",
      headline: "Isolate the segment causing sessions↑ + conversion↓ before changing spend",
      recommended_action:
        "Identify the GA4 source/medium and device segments responsible for the session increase vs prior 7 days, then compare engagement and conversion proxies for those segments before scaling spend or starting CRO.",
      measurement_plan: "Track purchase conversion rate by segment for 7 days and compare against baseline.",
      success_metrics: [{ metric_id: "derived.purchase_conversion_pct", note: "By source/medium + device segment" }],
      evaluation_window: { startDate: "2026-08-04", endDate: "2026-08-10" },
      stop_condition: "If funnel completion declines materially, pivot to checkout/funnel instrumentation.",
      review_by: in7d,
      reversibility: "reversible",
      estimated_effort_hours: 1.5,
      estimated_cost_cents: 0
    },
    evidence_edges: [],
    thesis_influence_trace: [],
    knowledge_gap_ids: [],
    scenario_ids_evaluated: [],
    resilience_score: null,
    fragile_assumptions: [],
    contingency_id: null,
    early_warning_indicators: []
  };

  // B) External opportunity fixture (must not win as direct operating action)
  const externalOpportunity: FusionCandidate = {
    candidate_id: "cand_external_opportunity",
    candidate_type: "external_opportunity_fixture",
    source_engine: "manual_fixture",
    source_engine_version: "fixture_v1",
    linked_finding_id: null,
    linked_hypothesis_ids: [],
    linked_opportunity_id: "opp_external_timeboxed",
    linked_recommendation_id: null,
    recommendation_fingerprint: null,
    affected_business_domains: ["brand", "partnerships"],
    affected_entities: [{ entity_id: "entity_event", role: "external_event", entity_type: "event" }],
    supporting_evidence_fact_ids: [],
    contradicting_evidence_fact_ids: [],
    missing_evidence: ["No internal buyer overlap evidence", "No historical performance evidence for this subject category"],
    internal_sources_used: [],
    external_signals_used: ["signal_external_moment_1"],
    external_signals_missing: ["internal fit corroboration"],
    expected_mechanism: "time-bounded cultural moment may increase attention",
    blocked_domain_constraints: [],
    strategic_guardrail_violations: [],
    confidence: {
      system: "explanation_confidence",
      level: "possible",
      score: null,
      reasons: ["External signal is credible and time-bounded."],
      blockers: ["Internal buyer evidence is missing."]
    },
    urgency: "high",
    risk: "medium",
    value_potential_proxy: 0.6,
    information_gain_value: 0.7,
    strategic_fit: 0.7,
    relevance_expires_at: in2d,
    current_regime: null,
    proposed_action: {
      action_key: "validate_external_moment_fit",
      category: "measurement",
      headline: "Validate internal fit before committing to an external moment",
      recommended_action:
        "Run a small validation: publish one high-quality teaser post and measure downstream intent (site visits, save/share rate, inquiry signals) to determine whether this external moment aligns with your premium collector audience.",
      measurement_plan: "Measure intent proxies for 48 hours; proceed only if quality signals exceed baseline.",
      success_metrics: [{ metric_id: "ga4.sessions_count", note: "Quality proxy only; no causal claim" }],
      evaluation_window: { startDate: "2026-08-04", endDate: "2026-08-05" },
      stop_condition: "If signals are weak or low-intent, do not allocate production time.",
      review_by: in2d,
      reversibility: "reversible",
      estimated_effort_hours: 2,
      estimated_cost_cents: 0
    },
    evidence_edges: [],
    thesis_influence_trace: [],
    knowledge_gap_ids: [],
    scenario_ids_evaluated: [],
    resilience_score: null,
    fragile_assumptions: [],
    contingency_id: null,
    early_warning_indicators: []
  };

  // C) Competitive intelligence fixture (premium-positioning conflict)
  const competitorMove: FusionCandidate = {
    candidate_id: "cand_competitor_move",
    candidate_type: "competitive_signal_fixture",
    source_engine: "manual_fixture",
    source_engine_version: "fixture_v1",
    linked_finding_id: null,
    linked_hypothesis_ids: [],
    linked_opportunity_id: "opp_competitor_move",
    linked_recommendation_id: null,
    recommendation_fingerprint: null,
    affected_business_domains: ["pricing", "brand"],
    affected_entities: [{ entity_id: "competitor_x", role: "competitor", entity_type: "artist" }],
    supporting_evidence_fact_ids: [],
    contradicting_evidence_fact_ids: [],
    missing_evidence: ["No internal evidence this strategy fits premium originals"],
    internal_sources_used: [],
    external_signals_used: ["signal_competitor_discount_push"],
    external_signals_missing: [],
    expected_mechanism: "competitor discounting may increase volume",
    blocked_domain_constraints: [],
    strategic_guardrail_violations: ["premium_positioning_violation"],
    confidence: {
      system: "explanation_confidence",
      level: "possible",
      score: null,
      reasons: ["Competitor appears to be pushing discounts."],
      blockers: ["Premium positioning conflict."]
    },
    urgency: "medium",
    risk: "high",
    value_potential_proxy: 0.5,
    information_gain_value: 0.2,
    strategic_fit: 0.0,
    relevance_expires_at: in7d,
    current_regime: null,
    proposed_action: {
      action_key: "copy_competitor_discounting",
      category: "discounting",
      headline: "Match competitor discounts",
      recommended_action: "Offer discounts to match competitor pricing.",
      measurement_plan: null,
      success_metrics: [],
      evaluation_window: null,
      stop_condition: null,
      review_by: in7d,
      reversibility: "partially_reversible",
      estimated_effort_hours: 1,
      estimated_cost_cents: 0
    },
    evidence_edges: [],
    thesis_influence_trace: [],
    knowledge_gap_ids: [],
    scenario_ids_evaluated: [],
    resilience_score: null,
    fragile_assumptions: [],
    contingency_id: null,
    early_warning_indicators: []
  };

  // D) Lower-priority internal candidate
  const lowerPriority: FusionCandidate = {
    candidate_id: "cand_lower_priority_internal",
    candidate_type: "lower_priority_internal",
    source_engine: "manual_fixture",
    source_engine_version: "fixture_v1",
    linked_finding_id: null,
    linked_hypothesis_ids: [],
    linked_opportunity_id: "opp_minor_site_copy",
    linked_recommendation_id: null,
    recommendation_fingerprint: null,
    affected_business_domains: ["website"],
    affected_entities: [],
    supporting_evidence_fact_ids: ["fact_site_speed"],
    contradicting_evidence_fact_ids: [],
    missing_evidence: ["Need segment proof this is a revenue driver"],
    internal_sources_used: ["website"],
    external_signals_used: [],
    external_signals_missing: [],
    expected_mechanism: "minor friction may reduce conversion",
    blocked_domain_constraints: [],
    strategic_guardrail_violations: [],
    confidence: {
      system: "explanation_confidence",
      level: "possible",
      score: null,
      reasons: ["Minor friction detected."],
      blockers: ["Low materiality."]
    },
    urgency: "low",
    risk: "low",
    value_potential_proxy: 0.2,
    information_gain_value: 0.2,
    strategic_fit: 0.6,
    relevance_expires_at: null,
    current_regime: null,
    proposed_action: {
      action_key: "fix_minor_website_friction",
      category: "website",
      headline: "Fix minor website friction",
      recommended_action: "Resolve a minor website friction point.",
      measurement_plan: "Measure conversion before/after.",
      success_metrics: [{ metric_id: "derived.purchase_conversion_pct", note: null }],
      evaluation_window: { startDate: "2026-08-04", endDate: "2026-08-10" },
      stop_condition: "If no change, deprioritize.",
      review_by: in7d,
      reversibility: "reversible",
      estimated_effort_hours: 2,
      estimated_cost_cents: 0
    },
    evidence_edges: [],
    thesis_influence_trace: [],
    knowledge_gap_ids: [],
    scenario_ids_evaluated: [],
    resilience_score: null,
    fragile_assumptions: [],
    contingency_id: null,
    early_warning_indicators: []
  };

  // E) Blocked candidate (Meta attribution)
  const blockedMeta: FusionCandidate = {
    candidate_id: "cand_meta_roas_scale",
    candidate_type: "blocked_recommendation",
    source_engine: "manual_fixture",
    source_engine_version: "fixture_v1",
    linked_finding_id: null,
    linked_hypothesis_ids: [],
    linked_opportunity_id: "opp_meta_scale",
    linked_recommendation_id: null,
    recommendation_fingerprint: null,
    affected_business_domains: ["marketing"],
    affected_entities: [],
    supporting_evidence_fact_ids: ["fact_meta_roas"],
    contradicting_evidence_fact_ids: [],
    missing_evidence: [],
    internal_sources_used: ["meta"],
    external_signals_used: [],
    external_signals_missing: [],
    expected_mechanism: "Meta ROAS improved",
    blocked_domain_constraints: ["meta_attribution_blocked"],
    strategic_guardrail_violations: [],
    confidence: {
      system: "explanation_confidence",
      level: "likely",
      score: null,
      reasons: ["Meta ROAS appears high."],
      blockers: []
    },
    urgency: "medium",
    risk: "medium",
    value_potential_proxy: 0.6,
    information_gain_value: 0.1,
    strategic_fit: 0.5,
    relevance_expires_at: null,
    current_regime: null,
    proposed_action: {
      action_key: "scale_spend",
      category: "scale",
      headline: "Scale Meta spend",
      recommended_action: "Scale Meta spend based on ROAS.",
      measurement_plan: "Track ROAS.",
      success_metrics: [{ metric_id: "meta.roas", note: null }],
      evaluation_window: { startDate: "2026-08-04", endDate: "2026-08-10" },
      stop_condition: "Stop if ROAS drops.",
      review_by: in7d,
      reversibility: "reversible",
      estimated_effort_hours: 1,
      estimated_cost_cents: 20000
    },
    evidence_edges: [],
    thesis_influence_trace: [],
    knowledge_gap_ids: [],
    scenario_ids_evaluated: [],
    resilience_score: null,
    fragile_assumptions: [],
    contingency_id: null,
    early_warning_indicators: []
  };

  // Include one expired example only through candidate modifications? Not allowed; must be five candidates.
  // We satisfy expiration test separately by cloning candidates in tests.

  return [trafficQuality, externalOpportunity, competitorMove, lowerPriority, blockedMeta];
}
